hc10_arm:
  kinematics_solver: hc10_kinect_ikfast/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.01
  kinematics_solver_timeout: 1.0
  goal_joint_tolerance: 0.05
  goal_position_tolerance: 0.05
  goal_orientation_tolerance: 0.05